#!/usr/bin/env python3
import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


STYLE_PREFIXES = {
    "solid": "fa-solid",
    "regular": "fa-regular",
    "brands": "fa-brands",
}


def parse_icon_ref(value):
    text = str(value).strip()
    if not text:
        return None
    if ":" not in text:
        raise ValueError(f"Icon reference must include a style prefix: {text}")
    style, name = text.split(":", 1)
    style = style.removeprefix("fa-")
    if style not in STYLE_PREFIXES:
        raise ValueError(f"Unsupported Font Awesome style: {style}")
    return style, name


def load_manifest(path):
    if path is None:
        return None

    data = json.loads(Path(path).read_text(encoding="utf-8"))
    icons = set()
    if isinstance(data, dict) and isinstance(data.get("icons"), list):
        for entry in data["icons"]:
            icons.add(parse_icon_ref(entry))
    else:
        for style, names in data.items():
            normalized_style = str(style).removeprefix("fa-")
            if normalized_style not in STYLE_PREFIXES:
                raise ValueError(f"Unsupported Font Awesome style in manifest: {style}")
            for name in names:
                icons.add((normalized_style, str(name).strip()))
    return icons


def parse_view_box(value):
    parts = [float(part) for part in re.split(r"[\s,]+", value.strip()) if part]
    if len(parts) != 4:
        raise ValueError(f"Invalid SVG viewBox: {value}")
    return parts


def qml_string(value):
    return json.dumps(value, ensure_ascii=False)


def qml_number(value):
    if int(value) == value:
        return str(int(value))
    return f"{value:.6f}".rstrip("0").rstrip(".")


def read_svg_icon(path):
    tree = ET.parse(path)
    root = tree.getroot()
    view_box = parse_view_box(root.attrib.get("viewBox", "0 0 0 0"))
    paths = []

    for element in root.iter():
        if element.tag.endswith("path"):
            path_data = element.attrib.get("d", "").strip()
            if path_data:
                paths.append(normalize_svg_path(path_data))

    if not paths:
        raise ValueError(f"No SVG paths found in {path}")

    return view_box, " ".join(paths)


def normalize_svg_path(path_data):
    # Qt's PathSvg is stricter than browser SVG parsers for compact path data.
    # Font Awesome emits strings like "M0 128C0 92.7..." while svgtoqml
    # normalizes them to "M 0 128 C 0 92.7 ...". Keep generated data in that
    # explicit form so Shape rendering stays deterministic.
    text = str(path_data).replace(",", " ")
    text = re.sub(r"([MmZzLlHhVvCcSsQqTtAa])", r" \1 ", text)
    text = re.sub(r"(?<=[0-9.])(-)", r" \1", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def collect_icons(source_dir, styles, manifest_icons):
    icons_dir = source_dir / "svgs"
    if not icons_dir.exists():
        raise FileNotFoundError(f"Font Awesome SVG directory not found: {icons_dir}")

    entries = []
    for style in styles:
        style_dir = icons_dir / style
        if not style_dir.exists():
            raise FileNotFoundError(f"Font Awesome style directory not found: {style_dir}")

        for svg_path in sorted(style_dir.glob("*.svg")):
            name = svg_path.stem
            if manifest_icons is not None and (style, name) not in manifest_icons:
                continue
            view_box, path_data = read_svg_icon(svg_path)
            entries.append((style, name, view_box, path_data))

    return entries


def write_registry(output, entries, source_label):
    lines = [
        "// Generated by tools/icons/generate_fontawesome_qml.py",
        f"// Source: {source_label}",
        "pragma Singleton",
        "import QtQuick",
        "",
        "QtObject {",
        "    id: root",
        "",
        "    readonly property var icons: ({",
    ]

    for index, (style, name, view_box, path_data) in enumerate(entries):
        comma = "," if index + 1 < len(entries) else ""
        key = f"{STYLE_PREFIXES[style]}:{name}"
        view_box_qml = "[" + ", ".join(qml_number(part) for part in view_box) + "]"
        lines.append(
            f"        {qml_string(key)}: "
            f"{{ \"style\": {qml_string(style)}, \"name\": {qml_string(name)}, "
            f"\"viewBox\": {view_box_qml}, \"path\": {qml_string(path_data)} }}{comma}"
        )

    lines.extend([
        "    })",
        "",
        "    function normalizeStyle(style) {",
        "        const value = String(style || \"solid\").trim()",
        "        if (value === \"fa\" || value === \"fas\" || value === \"fa-solid\")",
        "            return \"fa-solid\"",
        "        if (value === \"far\" || value === \"fa-regular\")",
        "            return \"fa-regular\"",
        "        if (value === \"fab\" || value === \"fa-brands\")",
        "            return \"fa-brands\"",
        "        if (value === \"solid\" || value === \"regular\" || value === \"brands\")",
        "            return \"fa-\" + value",
        "        return value",
        "    }",
        "",
        "    function normalizeName(iconName) {",
        "        return String(iconName || \"\").trim().toLowerCase().replace(/_/g, \"-\")",
        "    }",
        "",
        "    function normalizeIconRef(iconRef) {",
        "        const value = String(iconRef || \"\").trim()",
        "        if (value.indexOf(\":\") >= 0) {",
        "            const separator = value.indexOf(\":\")",
        "            return normalizeStyle(value.substring(0, separator)) + \":\" + normalizeName(value.substring(separator + 1))",
        "        }",
        "        return \"fa-solid:\" + normalizeName(value)",
        "    }",
        "",
        "    function resolve(iconRef) {",
        "        const key = normalizeIconRef(iconRef)",
        "        return icons[key] || null",
        "    }",
        "",
        "    function iconNames(style) {",
        "        const prefix = normalizeStyle(style) + \":\"",
        "        const result = []",
        "        const keys = Object.keys(icons)",
        "        for (let i = 0; i < keys.length; ++i) {",
        "            const key = keys[i]",
        "            if (key.indexOf(prefix) === 0)",
        "                result.push({ \"name\": icons[key].name, \"style\": icons[key].style })",
        "        }",
        "        result.sort(function(left, right) { return left.name.localeCompare(right.name) })",
        "        return result",
        "    }",
        "}",
        "",
    ])

    output.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Generate a QML Font Awesome SVG registry.")
    parser.add_argument("--source-dir", required=True, type=Path, help="Font Awesome package directory containing svgs/")
    parser.add_argument("--output", required=True, type=Path, help="Output FontAwesomeRegistry.qml path")
    parser.add_argument("--manifest", type=Path, help="Optional JSON manifest limiting generated icons")
    parser.add_argument("--styles", nargs="+", default=["solid", "regular", "brands"], choices=sorted(STYLE_PREFIXES.keys()))
    args = parser.parse_args()

    manifest_icons = load_manifest(args.manifest)
    entries = collect_icons(args.source_dir, args.styles, manifest_icons)
    if not entries:
        print("No Font Awesome icons selected", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_registry(args.output, entries, str(args.source_dir))
    print(f"Generated {len(entries)} Font Awesome icons at {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
